### ISSUE TITLE
Footer needs to stay at the bottom of a page, pages need to fill a window

### ISSUE THREAD

**Issue by shariq1989** [alexlanza/cs399_agency#10]
The issue I am seeing is that when the style="position:relative"; tag is used on the footer, it fixes the issue of the footer being placed at the end of the browser window but upon scrolling down, it moves with the page. Here is a screenshot of the issue.
![screen shot 2015-02-18 at 9 51 51 am](https://cloud.githubusercontent.com/assets/2559167/6251894/cffbe56c-b753-11e4-819e-4d82650c23bd.png)

When the tag is used, the footer is placed correctly at the bottom of the web page.. but the index, email and work pages are not the size of a webpage so the footer awkwardly hangs in the middle of the window. 

Is there a way to get the work, index and email pages to fill the browser window?

**Comment by shariq1989** [comment]
My first guess was using height="100%"; on a div that encapsulates the {% block content %} and {% endblock %} tags but it seems to not fix the issue.

**Comment by jpoehnelt** [comment]
probably just needs absolute
