### ISSUE TITLE
Splash page image

### ISSUE THREAD

**Issue by shariq1989** [alexlanza/cs399_agency#11]
I have been pulling my hair out on this one.  I am thinking the awards image can be placed in a jumbotron as a background. The "background-image" or "background" properties can be used with a "background-repeat:no-repeat" property. I just have not been able to get it to display properly.

**Comment by jpoehnelt** [comment]
[background-size: cover](http://www.w3schools.com/cssref/playit.asp?filename=playcss_background-size&preval=cover)

**Comment by jpoehnelt** [comment]
might want to modify image size
